name: JavaApp Tomcat-jenkins-Docker-kubernates CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: |
          TAG=${{ secrets.DOCKER_USERNAME }}/$IMAGE:${{ TAG }}
          docker pull $IMAGE:$TAG
          echo "Docker image pulled with tag $latest"

      - name: login-GitHub:
        needs: Login to GitHub
        runs-on: ubuntu-latest
        steps:
          - name: Checkout gitops repo
            uses: actions/checkout@v4
            with:
              repository: ammukaleem/saijava-gitops.git
              token: ${{ secrets.GITOPS_TOKEN }}
              path: saijava-gitops
              ref: main    
      - name: Update image in deployment manifest
        run: |
          IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/$IMAGE:${{ TAG }}
          cd saijava-gitops
          ls -lrt
          echo $IMAGE:$TAG
        sed -i "s|image: .*|image: $IMAGE:$TAG|g" ./tomcat-dep.yaml
          git config --global user.email ${{ vars.GIT_EMAIL }}
          git config --global user.name ${{ vars.GIT_USERNAME }}
          git add .
          git commit -m "Update image to $IMAGE:$TAG"
          git push origin main  
                  
