name: JavaApp Tomcat-jenkins-Docker-kubernates CI/CD

env:
  IMAGE: dockaleem/tomcat-app
  VERSION: "v1.0-${GITHUB_RUN_ID}"
  TOMCAT_HOME: /usr/local/tomcat

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # Correct indentation

jobs:

  checkout-code:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Code
         uses: actions/checkout@v4
         with:
           repository: ammukaleem/gitops-practice
           token: ${{ secrets.GITOPS_TOKEN }}
           path: gitops-practice
           ref: main
       - name: Debug Directory
         run: |
           pwd
           ls -l
         working-directory: gitops-practice 
       - name: Build WAR File with Maven
         run: mvn clean package
         working-directory: gitops-practice
       - name: Upload WAR file
         uses: actions/upload-artifact@v2
         with:
           name: webapp-war
           path: webapp/target/webapp-1.0-SNAPSHOT.war

       
          

