name: JavaApp Tomcat-jenkins-Docker-kubernates CI/CD

env:
  IMAGE: dockaleem/tomcat-app
  VERSION: "v1.0-${GITHUB_RUN_ID}"

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # Correct indentation

jobs:

  checkout-code:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Code
         uses: actions/checkout@v4
         with:
           repository: ammukaleem/gitops-practice
           token: ${{ secrets.GITOPS_TOKEN }}
           path: gitops-practice
           ref: main
       - name: Debug Directory
         run: |
           pwd
           ls -l
         working-directory: gitops-practice 
       - name: Maven Test
         run: mvn test
         working-directory: gitops-practice
  
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
    - name: copy war file from current directory to tomacat
      run: cp -R ./ /usr/local/tomcat/webapps

    - name: build Docker image
      run: docker build -t ${IMAGE}:${VERSION} .
  
  Push-Docker-image-to-Dockerhub:
    name: push
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push ${IMAGE}:${VERSION}  

           
  Pull-image-from-Dockerhub:
    name: pull
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: docker pull dockaleem/tomcat-app:latest  
      
  update-saijava-gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          repository: ammukaleem/saijava-gitops.git
          token: ${{ secrets.GITOPS_TOKEN }}
          path: saijava-gitops
          ref: main

      - name: Update image in deployment manifest
        run: |
        
          IMAGE=dockaleem/tomcat-app
          VERSION="v1.0-${GITHUB_RUN_ID}"
  
          echo "Using image: $IMAGE with tag: $VERSION"
          cd saijava-gitops
          ls -lrt
          sed -i "s|image: .*|image: $IMAGE:$VERSION|g" ./tomapp-dep.yaml
          git config --global user.name "${{ vars.GIT_USERNAME }}"
          git config --global user.email "${{vars.GIT_EMAIL }}"
          git add .
          git commit -m "Fix: image is $IMAGE:$VERSION"
          git push origin main  
           
          

