name: JavaApp Tomcat-jenkins-Docker-kubernates CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # Correct indentation

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
